 select
  "ELEM" as ?e
  if(str(?p) = "ELEM", "true", "false") as ?m
  "p" as ?f
  str(?s) as ?s
  str(?p) as ?p
  str(?o) as ?o
where {
  ?s ?p ?o
  filter(str(?p) = "ELEM" || regex(str(?p), "ELEM"))
}